/**
 * schema-codegen.test.ts — 决策 26 v1 留位兑现：编译产物流 schema 携带（schema 批 C）。
 *
 * 批动机（schema 批归档行）：dev 插件通道已通（transform prepend 注册调用），但编译产物
 * 通道未通——应用走 dump→codegen 产物 + registerCompiled 时 schema 没有随产物流动，compiled
 * 组件拿不到校验。本批冻结契约（主智能体钉死）：
 *   ① codegen：CLI main 读 dump 透传 schema → compileModuleSource(name, raws, {schema}) →
 *      产物在 `export const compiled` 之后仅当 schema 存在时追加
 *      `export const compiledSchema = <JSON 字面量>;`（确定性序列化 = regen 字节幂等）；
 *      schema 缺省时产物与加法前逐字节一致（硬约束，golden 钉死）。
 *   ② runtime registerCompiled：接受产物模块上的 compiledSchema；对每个携带 schema 的条目
 *      ⑴ 喂决策 26 sink（registerExtractedSchemas——接口冻结不改）⑵ 回填既有 registry 条目
 *      （仅当其 schema === undefined——显式 opts.schema 恒胜，决策 26 承诺逐字保持）。
 *   ③ 语义钉：时序无关——registerCompiled 先于/后于 component() 都生效。
 *
 * 红检素材：改动前 registerCompiled 携带 schema 被丢弃 → def.schema undefined →
 * validateProps no-op → 违例 props 静默通过（本文件端到端用例先红后绿）。
 * 隔离模式跟随 schema-sink.test.ts：beforeEach __resetExtractedSchemas（test-only 出口，
 * 不进生产路径）+ 组件名逐用例唯一防全局 registry 串扰。
 */
import "./dom-shim.ts";
import { beforeEach, describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { mountComponent, registerCompiled } from "../runtime/template.ts";
import type { ComponentDef, ComponentRegistry } from "../runtime/template.ts";
import { __resetExtractedSchemas, component, registerExtractedSchemas, registry } from "../runtime/component.ts";
import { validateFlat } from "../runtime/contract.ts";
import { compileFunction, compileModuleSource } from "../compiler/codegen.mjs";
import { findByTag } from "./dom-shim.ts";

const NODE_OK = (() => {
  const [maj, min] = process.versions.node.split(".").map(Number);
  return maj > 22 || (maj === 22 && min >= 18);
})();
const DUMP = path.resolve(__dirname, "..", "compiler", "dump.mjs");
const CODEGEN = path.resolve(__dirname, "..", "compiler", "codegen.mjs");

const flush = async (): Promise<void> => {
  await new Promise((r) => queueMicrotask(() => queueMicrotask(r)));
  await new Promise((r) => queueMicrotask(() => queueMicrotask(r)));
};

/** 提取产物同构形态（compiler/extract-schema.mjs 产物 / dump.schema 字段，纯 JSON） */
const FLAT_SCHEMA = {
  type: "object",
  reqProps: { title: { type: "string" } },
  optProps: {},
};

beforeEach(() => {
  __resetExtractedSchemas(); // 用例互不污染（test-only 内部出口，生产面不提供 clear）
});

/* ================= 编译发射面（compiler/codegen.mjs） ================= */

describe("决策 26 产物流：codegen 发射面", () => {
  it("opts.schema 存在 → 产物在 export const compiled 之后追加 compiledSchema；同输入两次生成字节一致（幂等）", () => {
    const raw = `<em>{props.title}</em>`;
    const s1 = compileModuleSource("SchemaEmit", [raw], { schema: FLAT_SCHEMA });
    const s2 = compileModuleSource("SchemaEmit", [raw], { schema: FLAT_SCHEMA });
    expect(s1).toBe(s2); // 确定性序列化 = regen 字节幂等（冻结契约①）
    expect(s1).toContain(`export const compiledSchema = ${JSON.stringify(FLAT_SCHEMA)};`);
    // 位次钉：追加位在 export const compiled 之后（冻结契约原文）
    expect(s1.indexOf("export const compiledSchema")).toBeGreaterThan(
      s1.indexOf("export const compiled = compiledList[0];"),
    );
  });

  it("schema 缺省 → 产物与加法前逐字节一致（golden 钉 = 冻结契约硬约束佐证）", () => {
    const src = compileModuleSource("GoldenPin", ["<em>{t.value}</em>"]);
    expect(src).toBe(
      `// generated by atelier/compiler/codegen.mjs (P0-2 stage ③) — do not edit by hand
// component: GoldenPin · schema: atelier-compiled/0.1 · 运行时能力经 ctx.rt 注入（__compiledRT）
// deps（F-2 静态依赖清单）＝ 语法级引用集 ⊇ 运行时追踪集（含未执行分支，已滤除 each 子作用域变量）
export const compiledList = [
  {
    name: "GoldenPin",
    deps: { reactive: ["t"], mount: [], events: [] },
    program(ctx) {
    const { scope, registry, validate, rt } = ctx;
    const frag = document.createDocumentFragment();
    {
      const el1 = document.createElement("em");
      const c2 = document.createDocumentFragment();
    const tn3 = document.createTextNode("");
    rt.bindExpr("t.value", scope, (v) => { tn3.textContent = rt.stringify(v); });
    c2.appendChild(tn3);
      el1.appendChild(c2);
      frag.appendChild(el1);
    }
    return frag;
    },
  },
];
export const compiled = compiledList[0];
`,
    );
  });

  it("CLI 全链：dump（(props:{...}) 注解）→ codegen 产物携带 compiledSchema（与 dump.schema 逐字一致）；无注解组件不携带；regen 字节幂等", (ctx) => {
    if (!NODE_OK) return ctx.skip();
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "atr-schema-codegen-"));
    fs.mkdirSync(path.join(dir, "src"), { recursive: true });
    // 注解组件：schema 随 dump.schema 字段流动（决策 26 提取面单一真相）
    fs.writeFileSync(
      path.join(dir, "src", "Annotated.atr.ts"),
      [
        'import { component, html } from "atelier/runtime";',
        "export const Annotated = component(function Annotated(props: { title: string }) {",
        "  return html`<section><h2>{props.title}</h2></section>`;",
        "});",
      ].join("\n"),
    );
    // 无注解组件：dump 无 schema 键 → 产物不得携带（向后兼容现状）
    fs.writeFileSync(
      path.join(dir, "src", "Plain.atr.ts"),
      [
        'import { component, html } from "atelier/runtime";',
        "export const Plain = component(function Plain() {",
        "  return html`<p>plain</p>`;",
        "});",
      ].join("\n"),
    );
    try {
      const dump = spawnSync(process.execPath, [DUMP, "--root", dir], { encoding: "utf8" });
      if (dump.status !== 0) throw new Error(`dump failed: ${dump.stderr}`);
      const astDir = path.join(dir, ".atr", "ast");
      const outDir = path.join(dir, ".atr", "compiled");
      const dumpAnnotated = JSON.parse(fs.readFileSync(path.join(astDir, "Annotated.json"), "utf8"));
      expect(dumpAnnotated.schema, "注解组件 dump 携带 schema（stage ② 提取面前提）").toBeTruthy();
      const dumpPlain = JSON.parse(fs.readFileSync(path.join(astDir, "Plain.json"), "utf8"));
      expect(dumpPlain.schema, "无注解组件 dump 无 schema 键").toBeUndefined();

      const runCodegen = () =>
        spawnSync(process.execPath, [CODEGEN, "--ast", astDir, "--out", outDir, "--quiet"], { encoding: "utf8" });
      const r1 = runCodegen();
      if (r1.status !== 0) throw new Error(`codegen failed: ${r1.stderr}`);
      const annotatedSrc = fs.readFileSync(path.join(outDir, "Annotated.mjs"), "utf8");
      expect(annotatedSrc).toContain(`export const compiledSchema = ${JSON.stringify(dumpAnnotated.schema)};`);
      expect(fs.readFileSync(path.join(outDir, "Plain.mjs"), "utf8")).not.toContain("compiledSchema");

      // regen 字节幂等：同 dump 输入重跑 → 产物逐字节一致
      const before = annotatedSrc;
      const r2 = runCodegen();
      if (r2.status !== 0) throw new Error(`codegen regen failed: ${r2.stderr}`);
      expect(fs.readFileSync(path.join(outDir, "Annotated.mjs"), "utf8")).toBe(before);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

/* ================= runtime 接收面（registerCompiled 携带 schema） ================= */

describe("决策 26 产物流：registerCompiled 接收面（时序无关双路径）", () => {
  it("端到端（sink 路径）：真实产物模块 import → registerCompiled → component() 无显式 schema → 坏 props 出 ATR-201 错误卡", async () => {
    const raw = `<em>{props.title}</em>`;
    const src = compileModuleSource("CompiledSchemaE2E", [raw], { schema: FLAT_SCHEMA });
    // 落盘真实产物 → 进程内 import（应用侧 `import * as mod` 形态同构：mod.compiled / mod.compiledSchema）
    const outDir = path.join(__dirname, "__schema_codegen_out__");
    fs.mkdirSync(outDir, { recursive: true });
    const file = path.join(outDir, "CompiledSchemaE2E.mjs");
    fs.writeFileSync(file, src, "utf8");
    try {
      const mod = (await import(pathToFileURL(file).href)) as {
        compiledList: unknown[];
        compiled: unknown;
        compiledSchema: unknown;
      };
      expect(mod.compiledSchema, "产物模块导出 compiledSchema").toEqual(FLAT_SCHEMA);
      registerCompiled(mod); // ← 改动前：compiledSchema 在此被丢弃
      const def = component(function CompiledSchemaE2E(props: { title?: string }) {
        return html`<em>{props.title}</em>`.locals({ props });
      }); // 无显式 schema（fn.name 同名 → 决策 26 defName 解析现序）
      expect(def.schema).toBe(mod.compiledSchema); // sink 兜底（同引用）

      const reg: ComponentRegistry = new Map();
      reg.set("CompiledSchemaE2E", def);
      const host: ComponentDef = {
        name: "CompiledSchemaE2EHost",
        render: () => ({ raw: `<section><CompiledSchemaE2E level={1} /></section>`, scope: {} }) as never,
      };
      reg.set("CompiledSchemaE2EHost", host);
      const container = document.createElement("div");
      mountComponent(host, {}, container, reg, validateFlat);
      await flush();
      // 红检主钉：改动前 def.schema undefined → validateProps no-op → 违例 props 静默渲染；
      // 兑现后缺 reqProps title 触发 ATR-201 错误卡（错误卡替换组件渲染，不白屏）
      expect(container.textContent).toContain("ATR-201");
      expect(container.textContent).toContain("缺少必填属性 title（string）");
      expect(findByTag(container, "em")).toBeNull();
    } finally {
      fs.rmSync(outDir, { recursive: true, force: true });
    }
  });

  it("端到端（回填路径）：先 component() 后 registerCompiled → def.schema 回填 + 坏 props 同样出错误卡（时序无关钉）", async () => {
    const raw = `<em>{props.title}</em>`;
    const def = component(function BackfillE2E(props: { title?: string }) {
      return html`<em>{props.title}</em>`.locals({ props });
    }); // 先求值：def.schema undefined（sink 此刻无条目）
    expect(def.schema).toBeUndefined();
    registerCompiled({
      compiled: compileFunction("BackfillE2E", raw),
      compiledSchema: FLAT_SCHEMA,
    });
    expect(def.schema).toBe(FLAT_SCHEMA); // ② 回填既有 registry 条目（同一对象引用）
    expect(registry.get("BackfillE2E")?.schema).toBe(FLAT_SCHEMA); // 全局 registry 视角同源

    const reg: ComponentRegistry = new Map();
    reg.set("BackfillE2E", def);
    const host: ComponentDef = {
      name: "BackfillE2EHost",
      render: () => ({ raw: `<section><BackfillE2E level={1} /></section>`, scope: {} }) as never,
    };
    reg.set("BackfillE2EHost", host);
    const container = document.createElement("div");
    mountComponent(host, {}, container, reg, validateFlat);
    await flush();
    expect(container.textContent).toContain("ATR-201"); // 后于 component() 注入同样进校验路径
    expect(findByTag(container, "em")).toBeNull();
  });

  it("显式 opts.schema 恒胜（两时序）：component({schema:X}) 后 registerCompiled 携带 Y → X 胜；sink 先有条目后显式注册 → X 胜", () => {
    const handwritten = { type: "object", reqProps: { title: { type: "string" } }, optProps: { note: { type: "string" } } };
    // 时序 A：先 component（显式）后 registerCompiled（携带 Y）——永不覆盖已定义 schema
    const defA = component(function ExplicitWinA(_props: Record<string, unknown>) {
      return html`<em>x</em>`;
    }, { name: "ExplicitWinA", schema: handwritten });
    registerCompiled({
      compiled: compileFunction("ExplicitWinA", `<em>y</em>`),
      compiledSchema: FLAT_SCHEMA,
    });
    expect(defA.schema).toBe(handwritten);
    // 时序 B：先 registerCompiled（sink 有条目）后 component（显式）——opts.schema 恒胜
    registerCompiled({
      compiled: compileFunction("ExplicitWinB", `<em>y</em>`),
      compiledSchema: FLAT_SCHEMA,
    });
    const defB = component(function ExplicitWinB(_props: Record<string, unknown>) {
      return html`<em>x</em>`;
    }, { name: "ExplicitWinB", schema: handwritten });
    expect(defB.schema).toBe(handwritten);
  });

  it("形态矩阵：{compiled}/{compiledList}/数组/单条 各形态 × compiledSchema 携带/缺省 组合不破", () => {
    const raw = `<i>{a.value}</i>`;
    // {compiled} + compiledSchema → 生效
    registerCompiled({ compiled: compileFunction("VariantA", raw), compiledSchema: FLAT_SCHEMA });
    expect(component((_p: Record<string, unknown>) => html`<em>x</em>`, { name: "VariantA" }).schema).toBe(FLAT_SCHEMA);
    // {compiledList} + compiledSchema → 生效（产物模块完整形态：compiledList/compiled/compiledSchema 并存）
    registerCompiled({ compiledList: [compileFunction("VariantB", raw)], compiledSchema: FLAT_SCHEMA });
    expect(component((_p: Record<string, unknown>) => html`<em>x</em>`, { name: "VariantB" }).schema).toBe(FLAT_SCHEMA);
    // 单条形态 + 条目级 schema（CompiledTemplate.schema 可选字段 = 按 entries 携带通道）
    const entryC = compileFunction("VariantC", raw) as ComponentDef & { schema?: unknown } as never;
    (entryC as unknown as { schema: unknown }).schema = FLAT_SCHEMA;
    registerCompiled(entryC);
    expect(component((_p: Record<string, unknown>) => html`<em>x</em>`, { name: "VariantC" }).schema).toBe(FLAT_SCHEMA);
    // 数组形态（无 compiledSchema 可言）→ 零 schema 副作用
    registerCompiled([compileFunction("VariantD", raw)]);
    expect(component((_p: Record<string, unknown>) => html`<em>x</em>`, { name: "VariantD" }).schema).toBeUndefined();
    // {compiled} 缺省 schema → 零副作用（既有调用面逐字不破）
    registerCompiled({ compiled: compileFunction("VariantE", raw) });
    expect(component((_p: Record<string, unknown>) => html`<em>x</em>`, { name: "VariantE" }).schema).toBeUndefined();
  });

  it("无 schema 携带 → sink 零副作用（registerExtractedSchemas 不被无关调用污染）", () => {
    registerCompiled({
      compiled: compileFunction("SinkUntouched", `<i>{a.value}</i>`),
    });
    // sink 若被误写同名条目，component() 兜底会拿到非 undefined schema——此处钉死零污染
    const def = component(function SinkUntouched(_props: Record<string, unknown>) {
      return html`<em>x</em>`;
    });
    expect(def.schema).toBeUndefined();
    // 对照：sink 直写仍照常工作（registerExtractedSchemas 接口冻结回归钉）
    registerExtractedSchemas({ SinkUntouchedDirect: FLAT_SCHEMA });
    expect(component((_p: Record<string, unknown>) => html`<em>x</em>`, { name: "SinkUntouchedDirect" }).schema).toBe(
      FLAT_SCHEMA,
    );
  });
});
